# Generated by Django 5.2.1 on 2025-05-22 02:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-description']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
